### ISSUE TITLE
Connecting to host crashes under some condition

### ISSUE THREAD

**Issue by invidian** [flexkube/libflexkube#238]
```
panic: runtime error: invalid memory address or nil pointer dereference
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xcbaded]
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1:
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1: goroutine 81 [running]:
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1: github.com/flexkube/libflexkube/pkg/host.(*host).Connect(0xc000e38890, 0x22ef180, 0xc000e38890, 0x0, 0x0)
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1:         github.com/flexkube/libflexkube@v0.4.3/pkg/host/host.go:86 +0x2d
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1: github.com/flexkube/libflexkube/pkg/container.(*hostConfiguredContainer).connectAndForward(0xc000e91a00, 0xc000994680, 0x1b, 0x0, 0x0, 0xc0009942c0, 0x14)
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1:         github.com/flexkube/libflexkube@v0.4.3/pkg/container/hostconfiguredcontainer.go:146 +0x5c
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1: github.com/flexkube/libflexkube/pkg/container.(*hostConfiguredContainer).withForwardedRuntime(0xc000e91a00, 0xc000d975f0, 0x0, 0x0)
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1:         github.com/flexkube/libflexkube@v0.4.3/pkg/container/hostconfiguredcontainer.go:167 +0xab
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1: github.com/flexkube/libflexkube/pkg/container.(*hostConfiguredContainer).Status(0xc000e91a00, 0xc000d29ef0, 0xc000d97648)
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1:         github.com/flexkube/libflexkube@v0.4.3/pkg/container/hostconfiguredcontainer.go:458 +0x8b
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1: github.com/flexkube/libflexkube/pkg/container.containersState.CheckState(0xc000d29ef0, 0xc00049a7e0, 0x0)
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1:         github.com/flexkube/libflexkube@v0.4.3/pkg/container/containersstate.go:62 +0xac
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1: github.com/flexkube/libflexkube/pkg/container.(*containers).CheckCurrentState(0xc0005b8980, 0x0, 0x0)
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1:         github.com/flexkube/libflexkube@v0.4.3/pkg/container/containers.go:182 +0x36
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1: github.com/flexkube/libflexkube/pkg/apiloadbalancer.(*apiLoadBalancers).CheckCurrentState(0xc000d279a0, 0x233fa80, 0xc000d279a0)
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1:         github.com/flexkube/libflexkube@v0.4.3/pkg/apiloadbalancer/api-loadbalancers.go:216 +0x33
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1: github.com/flexkube/terraform-provider-flexkube/flexkube.newResource(0x2302dc0, 0xc000c9e280, 0x1, 0x2302dc0, 0xc000c9e280, 0xc000d977c8, 0xc0004f0420)
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1:         github.com/flexkube/terraform-provider-flexkube/flexkube/util.go:206 +0xfc
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1: github.com/flexkube/terraform-provider-flexkube/flexkube.initialize(0x2326e00, 0xc000c9e000, 0x215ab10, 0xc0004f0401, 0x215f030, 0xc000d97840, 0x49cd4b, 0x233f7c0)
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1:         github.com/flexkube/terraform-provider-flexkube/flexkube/util.go:216 +0x65
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1: github.com/flexkube/terraform-provider-flexkube/flexkube.resourceRead.func1(0x233f840, 0xc0004f0420, 0xc000c9e000, 0x1cabfc0, 0xc000a00770, 0xc000bea640, 0xc000d978b0, 0x40e118)
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1:         github.com/flexkube/terraform-provider-flexkube/flexkube/util.go:248 +0x51
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000327e40, 0x233f7c0, 0xc00030ea40, 0xc000c9e000, 0x1cabfc0, 0xc000a00770, 0x0, 0x0, 0x0)
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1:         github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.3/helper/schema/resource.go:288 +0x1ea
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000327e40, 0x233f7c0, 0xc00030ea40, 0xc000159420, 0x1cabfc0, 0xc000a00770, 0xc0001a4270, 0x0, 0x0, 0x0)
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1:         github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.3/helper/schema/resource.go:555 +0x1cb
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1: github.com/hashicorp/terraform-plugin-sdk/v2/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc0001a6ee0, 0x233f7c0, 0xc00030ea40, 0xc0001aa900, 0xc0001a6ee0, 0xc0001a6ef0, 0x215f030)
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1:         github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.3/internal/helper/plugin/grpc_provider.go:572 +0x43b
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1: github.com/hashicorp/terraform-plugin-sdk/v2/internal/tfplugin5._Provider_ReadResource_Handler.func1(0x233f7c0, 0xc00030ea40, 0x1f5e180, 0xc0001aa900, 0xc00030ea40, 0x1e3b2c0, 0xc0001aa801, 0xc0005324c0)
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1:         github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.3/internal/tfplugin5/tfplugin5.pb.go:3276 +0x89
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1: github.com/hashicorp/terraform-plugin-sdk/v2/plugin.Serve.func3.1(0x233f880, 0xc000c68120, 0x1f5e180, 0xc0001aa900, 0xc0005324a0, 0xc0005324c0, 0xc000c09ba0, 0x49ce06, 0x1f1ba00, 0xc000c68120)
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1:         github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.3/plugin/serve.go:76 +0x87
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1: github.com/hashicorp/terraform-plugin-sdk/v2/internal/tfplugin5._Provider_ReadResource_Handler(0x1fd2560, 0xc0001a6ee0, 0x233f880, 0xc000c68120, 0xc0001aa8a0, 0xc000a0ede0, 0x233f880, 0xc000c68120, 0xc0006dc000, 0x9877)
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1:         github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.3/internal/tfplugin5/tfplugin5.pb.go:3278 +0x150
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0007996c0, 0x235a860, 0xc000315380, 0xc0002aeb00, 0xc000986630, 0x30997b0, 0x0, 0x0, 0x0)
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1:         google.golang.org/grpc@v1.32.0/server.go:1082 +0x522
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1: google.golang.org/grpc.(*Server).handleStream(0xc0007996c0, 0x235a860, 0xc000315380, 0xc0002aeb00, 0x0)
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1:         google.golang.org/grpc@v1.32.0/server.go:1405 +0xcc5
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0008f03f0, 0xc0007996c0, 0x235a860, 0xc000315380, 0xc0002aeb00)
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1:         google.golang.org/grpc@v1.32.0/server.go:746 +0xa5
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-04-01T18:24:51.059+0200 [DEBUG] plugin.terraform-provider-flexkube_v0.4.1:         google.golang.org/grpc@v1.32.0/server.go:744 +0xa5
```

**Comment by jsimomaa** [comment]
I also encountered this with the following configuration:

```terraform
locals {
  controller_ips = ["1.1.1.1"]
  controller_names = ["controller01"]
}

resource "flexkube_pki" "pki" {
  etcd {
    peers   = zipmap(local.controller_names, local.controller_ips)
    servers = zipmap(local.controller_names, local.controller_ips)
  }
}

resource "flexkube_etcd_cluster" "etcd" {
  pki_yaml = flexkube_pki.pki.state_yaml

  ssh {
    user     = "root"
    private_key = file("~/.ssh/id_ed25519")
  }

  dynamic "member" {
    for_each = flexkube_pki.pki.etcd[0].peers

    content {
      name               = member.key
      peer_address       = member.value
      server_address     = member.value

      host {
        ssh {
          address = member.value
          user     = "root"
          private_key = file("~/.ssh/id_ed25519")
        }
      }
    }
  }
}
```

```bash
2023-11-14T06:45:29.604Z [INFO]  Starting apply for flexkube_etcd_cluster.etcd
2023-11-14T06:45:29.604Z [TRACE] terraform.contextPlugins: Initializing provider "registry.terraform.io/flexkube/flexkube" to read its schema
2023-11-14T06:45:29.604Z [TRACE] terraform.contextPlugins: Initializing provider "registry.terraform.io/flexkube/flexkube" to read its schema
2023-11-14T06:45:29.611Z [TRACE] terraform.contextPlugins: Initializing provider "registry.terraform.io/flexkube/flexkube" to read its schema
2023-11-14T06:45:29.611Z [TRACE] terraform.contextPlugins: Initializing provider "registry.terraform.io/flexkube/flexkube" to read its schema
2023-11-14T06:45:29.620Z [TRACE] GRPCProvider: GetProviderSchema
2023-11-14T06:45:29.620Z [DEBUG] flexkube_etcd_cluster.etcd: applying the planned Create change
2023-11-14T06:45:29.620Z [TRACE] GRPCProvider: ApplyResourceChange
2023-11-14T06:45:29.620Z [TRACE] GRPCProvider: GetProviderSchema
2023-11-14T06:45:29.622Z [TRACE] provider.terraform-provider-flexkube_v0.9.0: Received request: @module=sdk.proto tf_proto_version=5.3 tf_provider_addr=provider tf_req_id=ecc40116-1e9c-717d-15bb-ee91f0d4eb9d tf_resource_type=flexkube_etcd_cluster @caller=github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/tf5server/server.go:808 tf_rpc=ApplyResourceChange timestamp=2023-11-14T06:45:29.622Z
2023-11-14T06:45:29.622Z [TRACE] provider.terraform-provider-flexkube_v0.9.0: Sending request downstream: tf_rpc=ApplyResourceChange @module=sdk.proto tf_proto_version=5.3 tf_provider_addr=provider @caller=github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/internal/tf5serverlogging/downstream_request.go:20 tf_req_id=ecc40116-1e9c-717d-15bb-ee91f0d4eb9d tf_resource_type=flexkube_etcd_cluster timestamp=2023-11-14T06:45:29.622Z
2023-11-14T06:45:29.623Z [INFO]  provider.terraform-provider-flexkube_v0.9.0: 2023/11/14 06:45:29 [DEBUG] setting computed for "state_sensitive" from ComputedKeys: timestamp=2023-11-14T06:45:29.623Z
2023-11-14T06:45:29.623Z [INFO]  provider.terraform-provider-flexkube_v0.9.0: 2023/11/14 06:45:29 [DEBUG] setting computed for "state" from ComputedKeys: timestamp=2023-11-14T06:45:29.623Z
2023-11-14T06:45:29.624Z [TRACE] provider.terraform-provider-flexkube_v0.9.0: Calling downstream: tf_req_id=ecc40116-1e9c-717d-15bb-ee91f0d4eb9d tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-sdk/v2@v2.28.0/helper/schema/resource.go:908 tf_provider_addr=provider tf_resource_type=flexkube_etcd_cluster @module=sdk.helper_schema timestamp=2023-11-14T06:45:29.623Z
2023-11-14T06:45:29.634Z [TRACE] provider.stdio: received data: channel=STDOUT len=84
2023-11-14T06:45:29.634Z [WARN]  unexpected data:
  registry.terraform.io/flexkube/flexkube:stdout=
  | Checking for stopped and missing containers
  | Configuring and creating new containers
  
2023-11-14T06:45:29.635Z [TRACE] provider.stdio: waiting for stdio data
2023-11-14T06:45:29.638Z [TRACE] provider.terraform-provider-flexkube_v0.9.0: Served request: @module=sdk.proto tf_proto_version=5.3 tf_provider_addr=provider tf_rpc=ApplyResourceChange @caller=runtime/panic.go:914 tf_req_id=ecc40116-1e9c-717d-15bb-ee91f0d4eb9d tf_resource_type=flexkube_etcd_cluster timestamp=2023-11-14T06:45:29.637Z
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0: panic: runtime error: invalid memory address or nil pointer dereference
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xc1b279]
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0: goroutine 113 [running]:
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0: github.com/flexkube/libflexkube/pkg/host.(*host).Connect(0xc0007a2510?)
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0:     github.com/flexkube/libflexkube@v0.10.0/pkg/host/host.go:86 +0x19
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0: github.com/flexkube/libflexkube/pkg/container.(*hostConfiguredContainer).connectAndForward(0x0?, {0x246e665, 0x1b})
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0:     github.com/flexkube/libflexkube@v0.10.0/pkg/container/hostconfiguredcontainer.go:146 +0x7e
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0: github.com/flexkube/libflexkube/pkg/container.(*hostConfiguredContainer).withForwardedRuntime(0xc0007a2500, 0xc0009b0a08)
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0:     github.com/flexkube/libflexkube@v0.10.0/pkg/container/hostconfiguredcontainer.go:167 +0x7f
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0: github.com/flexkube/libflexkube/pkg/container.(*hostConfiguredContainer).Configure(0x27e5e68?, {0xc000c17f80?, 0x0?, 0xc000c16e00?})
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0:     github.com/flexkube/libflexkube@v0.10.0/pkg/container/hostconfiguredcontainer.go:324 +0x5e
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0: github.com/flexkube/libflexkube/pkg/container.(*containers).ensureConfigured(0xc00096d8d8, {0xc000b0c204, 0xc})
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0:     github.com/flexkube/libflexkube@v0.10.0/pkg/container/containers.go:224 +0x12d
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0: github.com/flexkube/libflexkube/pkg/container.(*containers).ensureNewContainer(0xc00096d8d8, {0xc000b0c204, 0xc})
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0:     github.com/flexkube/libflexkube@v0.10.0/pkg/container/containers.go:451 +0x67
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0: github.com/flexkube/libflexkube/pkg/container.(*containers).Deploy(0xc00096d8d8)
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0:     github.com/flexkube/libflexkube@v0.10.0/pkg/container/containers.go:529 +0x38a
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0: github.com/flexkube/libflexkube/pkg/etcd.(*cluster).Deploy(0xc00096d320)
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0:     github.com/flexkube/libflexkube@v0.10.0/pkg/etcd/cluster.go:374 +0x162
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0: github.com/flexkube/terraform-provider-flexkube/flexkube.resourceEtcdCluster.resourceCreate.func1({0x27d7078?, 0xc0007beae0?}, 0x0?, {0x0?, 0x0?})
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0:     github.com/flexkube/terraform-provider-flexkube/flexkube/util.go:233 +0xab
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000802620, {0x27d7078, 0xc0007beae0}, 0xd?, {0x1f1ea40, 0xc000329358})
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0:     github.com/hashicorp/terraform-plugin-sdk/v2@v2.28.0/helper/schema/resource.go:778 +0x11b
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000802620, {0x27d7078, 0xc0007beae0}, 0xc000541930, 0xc000c16a80, {0x1f1ea40, 0xc000329358})
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0:     github.com/hashicorp/terraform-plugin-sdk/v2@v2.28.0/helper/schema/resource.go:909 +0xa7e
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0007f4000, {0x27d7078?, 0xc0007be9f0?}, 0xc0000bc730)
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0:     github.com/hashicorp/terraform-plugin-sdk/v2@v2.28.0/helper/schema/grpc_provider.go:1027 +0xdbc
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0: github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000792000, {0x27d7078?, 0xc0007be000?}, 0xc000b0e070)
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0:     github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/tf5server/server.go:821 +0x56a
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x2335e60?, 0xc000792000}, {0x27d7078, 0xc0007be000}, 0xc000b0e000, 0x0)
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0:     github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:422 +0x169
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00046c780, {0x27e2020, 0xc000a10680}, 0xc0006a0000, 0xc00091b530, 0x3a8a300, 0x0)
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0:     google.golang.org/grpc@v1.56.1/server.go:1337 +0xde7
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0: google.golang.org/grpc.(*Server).handleStream(0xc00046c780, {0x27e2020, 0xc000a10680}, 0xc0006a0000, 0x0)
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0:     google.golang.org/grpc@v1.56.1/server.go:1714 +0x9e7
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0: google.golang.org/grpc.(*Server).serveStreams.func1.1()
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0:     google.golang.org/grpc@v1.56.1/server.go:959 +0x8d
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0: created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 87
2023-11-14T06:45:29.640Z [DEBUG] provider.terraform-provider-flexkube_v0.9.0:     google.golang.org/grpc@v1.56.1/server.go:957 +0x165
2023-11-14T06:45:29.644Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2023-11-14T06:45:29.644Z [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/flexkube/flexkube/0.9.0/linux_amd64/terraform-provider-flexkube_v0.9.0 pid=248844 error="exit status 2"
2023-11-14T06:45:29.644Z [ERROR] plugin.(*GRPCProvider).ApplyResourceChange: error="rpc error: code = Unavailable desc = error reading from server: EOF"
2023-11-14T06:45:29.644Z [TRACE] maybeTainted: flexkube_etcd_cluster.etcd encountered an error during creation, so it is now marked as tainted
```
